services:
  db:
    image: postgres:17
    container_name: postgres_db
    restart: unless-stopped
    env_file:
      - ./db_service/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./db_service/init:/docker-entrypoint-initdb.d запускаемый скрипт при первом развертывании
    networks:
      - internal
    expose:
      - 5432
    ports:
    - "5432:5432"
    mem_limit: 256m
    cpus: "0.3"

  pgadmin: 
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: unless-stopped
    environment:
      # PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      # PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"  # Открываем порт наружу, чтобы ты мог зайти в браузере
    networks:
      - internal
    command: gunicorn --bind 0.0.0.0:80 myapp:app

  xui_service:
    build: ./3x_ui
    container_name: xui_service
    restart: unless-stopped
    env_file:
      - ./3x_ui/.env
    networks:
      - internal
    ports:
      - "8001:8001"  # порт для 3x-ui API
    mem_limit: 160m
    cpus: "0.2"
    
  payment_service:
    build: ./payment_service
    container_name: payment_service
    restart: unless-stopped
    env_file:
      - ./payment_service/.env
    networks:
      - internal
    ports:
      - "8015:8015"
    mem_limit: 160m
    cpus: "0.2"

  bot:
    build: ./bot
    container_name: bot
    restart: unless-stopped
    env_file:
      - ./bot/.env
    networks:
      - internal
    # ports:
    #   - "5678:5678"  # порт для дебаггера
    # command: >
    #   sh -c "python -m debugpy --listen 0.0.0.0:5678 --wait-for-client main.py"
    mem_limit: 128m
    cpus: "0.2"
    command: python main.py

  db_service:
    build: ./db_service
    container_name: db_service
    restart: unless-stopped
    env_file:
      - ./db_service/.env
    volumes:
      - ./db_service:/app
    depends_on:
      - db
    networks:
      - internal
    expose:
      - 8000
    mem_limit: 128m
    cpus: "0.2"
    ports:
      - "8000:8000"

volumes:
  postgres_data:

networks:
  internal:
    driver: bridge
