services:

  remnawave_service:
    build: ./remnawave_service
    container_name: remnawave_service
    restart: unless-stopped
    env_file:
      - ./remnawave_service/.env
    networks:
      - internal
    ports:
      - "8002:8002"  # порт для 3x-ui API
    mem_limit: 160m
    cpus: "0.2"

  bot: 
    build: ./bot
    container_name: bot
    restart: unless-stopped
    env_file:
      - ./bot/.env
    networks:
      - internal
    # ports:
    #   - "5678:5678"  # порт для дебаггера
    # command: >
    #   sh -c "python -m debugpy --listen 0.0.0.0:5678 --wait-for-client main.py"
    mem_limit: 128m
    cpus: "0.2"
    command: python main.py

volumes:
  postgres_data:

networks:
  internal:
    name: internal
    driver: bridge

