"""Добавление полей для уведомлений

Revision ID: 42792730a221
Revises: 09407def9f25
Create Date: 2025-08-19 16:52:48.952176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42792730a221'
down_revision: Union[str, Sequence[str], None] = '09407def9f25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keys', sa.Column('warned', sa.Boolean(), nullable=True))
    op.add_column('keys', sa.Column('expired_warned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('keys', 'expired_warned')
    op.drop_column('keys', 'warned')
    # ### end Alembic commands ###
