"""Убрана опциональность флагов warned, expired_warned

Revision ID: 8bba362430cb
Revises: 42792730a221
Create Date: 2025-08-29 11:43:24.166402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bba362430cb'
down_revision: Union[str, Sequence[str], None] = '42792730a221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('keys', 'warned',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('keys', 'expired_warned',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('keys', 'expired_warned',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('keys', 'warned',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
