name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: secrets

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo -e "Host *\n  StrictHostKeyChecking no\n  IdentityFile ~/.ssh/id_ed25519\n" > ~/.ssh/config

      - name: Setup Git SSH Key on server
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
              mkdir -p ~/.ssh &&
              echo '${{ secrets.GIT_DEPLOY_KEY }}' > ~/.ssh/id_git &&
              chmod 600 ~/.ssh/id_git &&
              printf 'Host github.com\n  IdentityFile ~/.ssh/id_git\n  StrictHostKeyChecking no\n' >> ~/.ssh/config
            "

      - name: Prepare project dir on server
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            echo '📂 Подготавливаю /srv/dotnetdon_project'
            sudo mkdir -p /srv/dotnetdon_project
            sudo chown -R ${{ secrets.SSH_USER }}:${{ secrets.SSH_USER }} /srv/dotnetdon_project
            sudo chmod -R 755 /srv/dotnetdon_project
          "
          
      - name: Clone Repo if not exists
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
            if ! command -v git &> /dev/null; then
              echo "📦 Git не найден, устанавливаю..."
              if [ -f /etc/debian_version ]; then
                sudo apt update && sudo apt install -y git
              elif [ -f /etc/redhat-release ]; then
                sudo yum install -y git
              else
                echo "❌ Неизвестная ОС, git нужно ставить руками" && exit 1
              fi
            fi
      
            if [ ! -d /srv/dotnetdon_project/.git ]; then
              git clone git@github.com:sauvingnon/dotnetdon.git /srv/dotnetdon_project
            fi
          '

      - name: Create env files on server
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
              echo '${{ secrets.BOT_ENV_FILE }}' > /srv/dotnetdon_project/services/bot/.env &&
              echo '${{ secrets.DB_ENV_FILE }}' > /srv/dotnetdon_project/services/db_service/.env &&
              echo '${{ secrets.PANEL_ENV_FILE }}' > /srv/dotnetdon_project/services/remnawave_service/.env &&
              echo '${{ secrets.PAYMENT_ENV_FILE }}' > /srv/dotnetdon_project/services/payment_service/.env
            "

      - name: Deploy over SSH
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
            cd /srv/dotnetdon_project/services &&
            export PGADMIN_DEFAULT_EMAIL='${{ secrets.PGADMIN_EMAIL }}' &&
            export PGADMIN_DEFAULT_PASSWORD='${{ secrets.PGADMIN_PASSWORD }}' &&
            git reset --hard origin/master &&
            git pull origin master &&
            sudo docker compose down &&
            sudo docker compose up -d --build
          '
      
      - name: Проверка контейнеров
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
            echo "🔍 Контейнеры:"
            sudo docker ps
            echo ""
            echo "🚨 Проверка: все сервисы running?"
            FAIL=0
            for c in bot db_service payment_service remnawave_service postgres_db pgadmin4; do
              STATUS=$(sudo docker inspect -f "{{.State.Status}}" ${c} || echo "missing")
              echo "$c -> $STATUS"
              if [ "$STATUS" != "running" ]; then
                echo "❌ Контейнер $c не работает"
                FAIL=1
              fi
            done
            exit $FAIL
          '

